# Generated by Django 5.1.5 on 2025-02-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('mobile', models.BigIntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
