# Generated by Django 5.1.5 on 2025-02-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_verification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification_otp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
