# Generated by Django 5.1.5 on 2025-02-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_verification_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_otp',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
