# Generated by Django 5.1.5 on 2025-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_verification_otp_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification_otp',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='verification_otp',
            name='time',
        ),
        migrations.AddField(
            model_name='verification_otp',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
