# Generated by Django 5.1.5 on 2025-02-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0007_remove_verification_otp_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
