# Generated by Django 5.1.5 on 2025-02-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0010_alter_userdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=1000)),
                ('data', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
