# Generated by Django 5.1.5 on 2025-02-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0011_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(max_length=1000)),
                ('name', models.CharField(max_length=600)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
