# Generated by Django 5.1.5 on 2025-02-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0012_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='name',
            new_name='domain_username',
        ),
        migrations.AddField(
            model_name='credentials',
            name='username',
            field=models.CharField(default='null', max_length=600),
        ),
    ]
