# Generated by Django 5.1.6 on 2025-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0013_rename_name_credentials_domain_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='unique_key',
            field=models.CharField(default=123456, max_length=6, unique=True),
        ),
    ]
