# Generated by Django 5.1.6 on 2025-02-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0015_alter_userdata_unique_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credentials',
        ),
    ]
