# Generated by Django 5.1.6 on 2025-02-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0016_delete_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
