# Generated by Django 5.1.6 on 2025-02-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0017_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('unique_key', models.CharField(default=0, max_length=6, unique=True)),
            ],
        ),
    ]
